# Decay - Makes your alacritty look smooth, soft and fancy

schemes:
  # Dark Theme
  decay_dark: &dark
    primary:
      background: '#171a1f'
      foreground: '#a9b1d6'

    cursor:
      cursor: '#f5f5f5'

    normal:
      black:   '#1C252C'
      red:     '#e05f65'
      green:   '#78dba9'
      yellow:  '#f1cf8a'
      blue:    '#70a5eb'
      magenta: '#c68aee'
      cyan:    '#74bee9'
      white:   '#dee1e6'

    bright:
      black:   '#384148'
      red:     '#fc7b81'
      green:   '#94f7c5'
      yellow:  '#ffeba6'
      blue:    '#8cc1ff'
      magenta: '#e2a6ff'
      cyan:    '#90daff'
      white:   '#fafdff'

  # Light Theme
  decay_light: &light
    primary:
      background: '#DFE2E7'
      foreground: '#22262e'

    cursor:
      cursor: '#171a1f'

    normal:
      black:   '#1c252c'
      red:     '#e05f65'
      green:   '#7dc086'
      yellow:  '#e9a180'
      blue:    '#70a5eb'
      magenta: '#c68aee'
      cyan:    '#74bee9'
      white:   '#dee1e6'

    bright:
      black:   '#384148'
      red:     '#fc7b81'
      green:   '#78dba9'
      yellow:  '#ecca85'
      blue:    '#8cc1ff'
      magenta: '#e2a6ff'
      cyan:    '#90daff'
      white:   '#fafdff'

colors:
  *dark

env:
  TERM: xterm-256color

window:
  dynamic_padding: true

  padding:
    x: 25
    y: 25

font:
  normal:
    family: Iosevka Semibold Extended
    style: Regular

  bold:
    family: Iosevka Semibold Extended
    style: Bold

  italic:
    family: Iosevka Semibold Extended
    style: Italic

  bold_italic:
    family: Iosevka Semibold Extended
    style: Bold Italic

  size: 14

  offset:
    x: 0
    y: 0

cursor:
  style: Beam

live_config_reload: true
