#!/bin/sh

symbol() {
    [ $(cat /sys/class/net/w*/operstate) = down ] && echo  && exit
    echo 
}

name() {
    nmcli | grep "^wlp4s0" | sed 's/\ connected\ to\ /Connected to /g' | cut -d ':' -f2
}

color() {
    [ $(cat /sys/class/net/w*/operstate) = down ] && echo "#e05f65" && exit
    echo "#70a5eb"
}

[ "$1" = "icon" ] && symbol && exit
[ "$1" = "name" ] && name && exit
[ "$1" = "color" ] && color && exit
