#!/bin/bash

DATA=$(curl -sf "localhost:8080/api/rand?level={n4}")
EN=$(echo $DATA | jq '."data"."en"')
KANJI=$(echo $DATA | jq '."data"."kanji"')

case $1 in 
  en)
    echo $EN
    ;;
  kanji)
    echo $KANJI
    ;;
esac
