#!/bin/sh

symbol() {
[ $(cat /sys/class/net/w*/operstate) = down ] && echo "" && exit
echo 
}

name() {
nmcli | grep "^wlp" | sed 's/\ connected\ to\ / /g' | cut -d ':' -f2
}

stats(){
  awk '{if(l1){print (($2-l1)/1024)/1000"mB/s",(($10-l2)/1024)/1000"mB/s"} else{l1=$2; l2=$10;}}' <(grep wlp4s0 /proc/net/dev) <(sleep 1; grep wlp4s0 /proc/net/dev)
}

color(){
  [ $(cat /sys/class/net/w*/operstate) = down ] && echo "#e05f65" && exit
  echo "#78bee9"
}


[ "$1" = "icon" ] && symbol && exit
[ "$1" = "name" ] && name && exit
[ "$1" = "stats" ] && stats && exit
[ "$1" = "color" ] && color && exit
