#!/bin/sh
# Enable double borders
# Dependencies: chwb2 from wmutils/opt
#
# Yes, this is stolen from gk.

outer='0x171a1f'   # outer
inner1='0x70a5eb'  # focused
inner2='0x22262e'  # normal

trap 'bspc config border_width 0; kill -9 -$$' INT TERM

targets() {
 	case $1 in
		focused) bspc query -N -n .local.focused.\!fullscreen;;
		normal)  bspc query -N -n .local.\!focused.\!fullscreen
	esac | grep -iv "$v"
}

bspc config border_width 18

draw() { chwb2 -I "$inner" -O "$outer" -i "5" -o "10" $* |:; }

# initial draw, and then subscribe to events
{ echo; bspc subscribe node_geometry node_focus; } |
 	while read -r _; do
		[ "$v" ] || v='abcdefg'
		inner=$inner1 draw "$(targets focused)"
		inner=$inner2 draw "$(targets normal)"
    done
