#!/bin/sh
status=$(mpc status | head -2 | tail -1 | cut -c2-7 )
icon=""
[ "$status" = "playin" ] && icon=""
[ "$status" = "paused" ] && icon=""
echo "$icon"

# if ps -C spotify > /dev/null; then
#     PLAYER="spotify"
# fi
#
# if [ -z "$PLAYER" ]; then
#     printf ""
# fi
#
# if [ "$PLAYER" = "spotify" ]; then
#     STATUS=$(playerctl -p spotify status)
#
#     if [ "$STATUS" = "Playing" ]; then
#         STATUS=""
#     else
#         STATUS=""
#     fi
#    
#     if [ "$PLAYER" = "spotify" ]; then
#         printf "$STATUS"
#     fi
# fi
